---
  - name: install vsftpd
    yum: 
      name: vsftpd
      state: present
    notify:
      - selinux change

  - name: copy vsftpd.conf to /etc/vsftpd.conf
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
      force: yes
    notify: restart vsftpd

  - name: create /var/ftp/pub/upload
    file:
      path: /var/ftp/pub/upload
      state: directory
      owner: ftp
      group: ftp
      mode: '777'

  - name: change chmod /var/ftp/pub
    file:
      path: /var/ftp/pub
      mode: '755'

  - name: firewalld allow ports
    firewalld:
      service: ftp
      permanent: yes
      immediate: yes
      state: enabled
      zone: public
     
