---
- hosts: all
  tasks:
 
    - name: Change /etc/defaut/grub
      lineinfile:
        dest: /etc/default/grub_bak
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames=0 biosdevname=0)\"[^\"]+)(\".*)'
        state: present
        line: '\1 net.ifnames=0 biosdevname=0\2'
        backrefs: yes
      

    - name: Execute grub2-mkconfig
      command:
        cmd: grub2-mkconfig


