---
  - name: Installs httpd web server
    yum:
      name: httpd
      state: latest
    notify: start httpd 

  - name: open http firewall port
    firewalld:
      service: http
      zone: public
      immediate: yes # this is the firewall-cmd --reload
      permanent: true
      state: enabled

  - name: Create file
    file:
      path: /var/www/html/index.html
      state: touch

  - name: Copy content to file
    template:
      dest: /var/www/html/index.html
      force: yes
      src: index.j2
